resources:
  containers:
    - container: browsers
      image: circleci/python:3.6.2-stretch-browsers
      options: -e FLASK_CONFIG=testing -e TEST_DATABASE_URL=postgresql://ubuntu@localhost/circle_test?sslmode?disable -u 0
    - container: database
      image: circleci/postgres:9.6.5-alpine-ram
      options: -e POSTGRES_USER=ubuntu -e POSTGRES_DB=circle_test -e POSTGRES_PASSWORD=""
phases:
  - phase: test
    steps:
    - script: |
        ps -a
      container: database
    - script: |
        curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      container: browsers
      displayName: Download Selenium
    - script: |
        java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log &
    - script: |
        python3 -m venv venv
        . venv/bin/activate
        pip install -r requirements/dev.txt
      container: browsers
      displayName: Install Python deps in a venv
    - script: |
        . venv/bin/activate
        python manage.py test
      displayName: Run Tests
    - script: |
        ps -a
      container: database


